-- 本地项目与会话表：仿 Codex app 的 project -> session -> message 结构

CREATE TABLE IF NOT EXISTS project (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    name VARCHAR(255) NOT NULL,
    root_path VARCHAR(2048),
    source_type VARCHAR(32) NOT NULL DEFAULT 'browser_directory',
    is_git_repo BOOLEAN NOT NULL DEFAULT FALSE,
    file_count INTEGER NOT NULL DEFAULT 0,
    dir_count INTEGER NOT NULL DEFAULT 0,
    file_samples TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_project_user_root_path UNIQUE (user_id, root_path)
);

CREATE INDEX IF NOT EXISTS idx_project_user_id ON project (user_id);

CREATE TABLE IF NOT EXISTS project_session (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'idle',
    last_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_project_session_project_id ON project_session (project_id);

CREATE TABLE IF NOT EXISTS session_message (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES project_session(id) ON DELETE CASCADE,
    role VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'done',
    tool_summary TEXT NOT NULL DEFAULT '[]',
    diff_summary TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_session_message_session_id ON session_message (session_id);

ALTER TABLE project ALTER COLUMN root_path DROP NOT NULL;
ALTER TABLE project ALTER COLUMN source_type SET DEFAULT 'browser_directory';
