-- Agent 后台任务表：支持刷新页面 / 新开会话后恢复任务进度

CREATE TABLE IF NOT EXISTS agent_task (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL UNIQUE,
    conversation_id VARCHAR(64),
    title VARCHAR(255),
    prompt TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    result TEXT,
    error_message TEXT,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_agent_task_task_id ON agent_task (task_id);
CREATE INDEX IF NOT EXISTS idx_agent_task_status ON agent_task (status);
CREATE INDEX IF NOT EXISTS idx_agent_task_conversation_id ON agent_task (conversation_id);
CREATE INDEX IF NOT EXISTS idx_agent_task_created_at ON agent_task (created_at);

CREATE TABLE IF NOT EXISTS agent_task_event (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    seq INTEGER NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    content TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_agent_task_event_task_seq UNIQUE (task_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_agent_task_event_task_id ON agent_task_event (task_id);
CREATE INDEX IF NOT EXISTS idx_agent_task_event_created_at ON agent_task_event (created_at);
